/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * buttons1.java
 *
 * Created on Jun 28, 2015, 11:09:56 AM
 */
package studentmanagement;

/**
 *
 * @author PARVINDER
 */
public class buttons1 extends javax.swing.JInternalFrame {

    /** Creates new form buttons1 */
    public buttons1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(studentmanagement.StudentManagementApp.class).getContext().getResourceMap(buttons1.class);
        jButton13.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton13.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton13.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton13.setText(resourceMap.getString("jButton13.text")); // NOI18N
        jButton13.setName("jButton13"); // NOI18N
        jPanel1.add(jButton13);
        jButton13.setBounds(130, 470, 300, 70);

        jButton10.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton10.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton10.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton10.setText(resourceMap.getString("jButton10.text")); // NOI18N
        jButton10.setName("jButton10"); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(540, 370, 300, 70);

        jButton12.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton12.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton12.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton12.setText(resourceMap.getString("jButton12.text")); // NOI18N
        jButton12.setName("jButton12"); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(130, 380, 300, 70);

        jButton9.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton9.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton9.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(540, 280, 300, 70);

        jButton4.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton4.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton4.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(120, 200, 300, 70);

        jButton7.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton7.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton7.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(540, 190, 300, 70);

        jButton14.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton14.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton14.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton14.setText(resourceMap.getString("jButton14.text")); // NOI18N
        jButton14.setName("jButton14"); // NOI18N
        jPanel1.add(jButton14);
        jButton14.setBounds(540, 470, 300, 70);

        jButton1.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton1.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 100, 300, 70);

        jButton5.setBackground(resourceMap.getColor("jButton5.background")); // NOI18N
        jButton5.setFont(resourceMap.getFont("jButton5.font")); // NOI18N
        jButton5.setForeground(resourceMap.getColor("jButton5.foreground")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(350, 560, 720, 70);

        jButton11.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton11.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton11.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton11.setText(resourceMap.getString("jButton11.text")); // NOI18N
        jButton11.setName("jButton11"); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(120, 290, 300, 70);

        jButton8.setBackground(resourceMap.getColor("jButton12.background")); // NOI18N
        jButton8.setFont(resourceMap.getFont("jButton12.font")); // NOI18N
        jButton8.setForeground(resourceMap.getColor("jButton12.foreground")); // NOI18N
        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(540, 100, 300, 70);

        jLabel1.setBackground(resourceMap.getColor("jLabel1.background")); // NOI18N
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 20, 790, 40);

        jButton2.setBackground(resourceMap.getColor("jButton16.background")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton16.font")); // NOI18N
        jButton2.setForeground(resourceMap.getColor("jButton16.foreground")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(930, 150, 250, 70);

        jButton3.setBackground(resourceMap.getColor("jButton16.background")); // NOI18N
        jButton3.setFont(resourceMap.getFont("jButton16.font")); // NOI18N
        jButton3.setForeground(resourceMap.getColor("jButton16.foreground")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(930, 260, 250, 70);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(studentmanagement.StudentManagementApp.class).getContext().getActionMap(buttons1.class, this);
        jButton15.setAction(actionMap.get("quit")); // NOI18N
        jButton15.setBackground(resourceMap.getColor("jButton16.background")); // NOI18N
        jButton15.setFont(resourceMap.getFont("jButton16.font")); // NOI18N
        jButton15.setForeground(resourceMap.getColor("jButton16.foreground")); // NOI18N
        jButton15.setText(resourceMap.getString("jButton15.text")); // NOI18N
        jButton15.setName("jButton15"); // NOI18N
        jPanel1.add(jButton15);
        jButton15.setBounds(930, 480, 250, 70);

        jButton16.setBackground(resourceMap.getColor("jButton16.background")); // NOI18N
        jButton16.setFont(resourceMap.getFont("jButton16.font")); // NOI18N
        jButton16.setForeground(resourceMap.getColor("jButton16.foreground")); // NOI18N
        jButton16.setText(resourceMap.getString("jButton16.text")); // NOI18N
        jButton16.setName("jButton16"); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(930, 370, 250, 70);

        jLabel4.setIcon(resourceMap.getIcon("jLabel4.icon")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-6, 4, 1210, 630);

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(550, 0, 840, 650);

        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1210, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 this.setVisible(false);
StudentManagementView.mainPanel.add(new studentrecord()).setVisible(true);
repaint();
validate(); 
        
        
        
        
    }
        /*
        this.setVisible(false);         RascalView.mainPanel.add(new newrecord1()).setVisible(true);         repaint();         validate();// TODO add your handling code here:}//GEN-LAST:event_jButton10ActionPerformed
*/
        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

            
        }
            /*
// TODO add your handling code here:}//GEN-LAST:event_jButton4ActionPerformed
*/
        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
}
            
            
            
            /*
        this.setVisible(false);         RascalView.mainPanel.add(new vissiondeptt()).setVisible(true);         repaint();         validate();// TODO add your handling code here:}//GEN-LAST:event_jButton7ActionPerformed
*/
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);        
StudentManagementView.mainPanel.add(new studentrecord1()).setVisible(true);       
repaint();  
validate();
        }
        /*
        this.setVisible(false);         RascalView.mainPanel.add(new studentrecord()).setVisible(true);         repaint();         validate();// TODO add your handling code here:}//GEN-LAST:event_jButton1ActionPerformed
*/
        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

            
            
            
        } 
            /*
// TODO add your handling code here:}//GEN-LAST:event_jButton5ActionPerformed
*/
        private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
}
        /*
        this.setVisible(false);         RascalView.mainPanel.add(new mission()).setVisible(true);         repaint();         validate();// TODO add your handling code here:}//GEN-LAST:event_jButton8ActionPerformed
*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      this.setVisible(false);
StudentManagementView.mainPanel.add(new add_view()).setVisible(true);
repaint();
validate();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
     this.setVisible(false);
StudentManagementView.mainPanel.add(new fee_detail()).setVisible(true);
repaint();
validate();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 this.setVisible(false);       // TODO add your handling code here:  this.setVisible(false);
StudentManagementView.mainPanel.add(new student_attendence1()).setVisible(true);
repaint();
validate();  
    }//GEN-LAST:event_jButton12ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
