/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newrecord1.java
 *
 * Created on Jun 26, 2015, 9:06:23 PM
 */
package studentmanagement;

import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.sun.xml.internal.bind.v2.model.core.ID;
import javax.swing.JOptionPane;

//import rascal.service.updateOperationDB;
import studentManagement.template.personalinfotemplate;
import studentmanagement.service.newrecordOperationDB;

/**
 *
 * @author PARVINDER
 */
public class newrecord1 extends javax.swing.JInternalFrame {
    private String bloodgp;

    /** Creates new form newrecord1 */
    public newrecord1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox14 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jComboBox16 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox();
        jComboBox18 = new javax.swing.JComboBox();
        jComboBox19 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(studentmanagement.StudentManagementApp.class).getContext().getResourceMap(newrecord1.class);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1270, 250);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 430, 79, 14);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 460, 88, 14);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 490, 38, 14);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 520, 37, 14);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 520, 39, 14);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 260, 70, 14);

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 310, 90, 14);

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        jPanel1.add(jLabel27);
        jLabel27.setBounds(20, 400, 50, 14);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(410, 260, 130, 20);

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(150, 300, 130, 20);

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(150, 430, 130, 20);

        jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(150, 460, 130, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "Male", "Female" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(150, 400, 130, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "B.Tech", "M.Tech." }));
        jComboBox2.setName("jComboBox2"); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(150, 490, 130, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "A1", "A2", "A3", "A4" }));
        jComboBox4.setName("jComboBox4"); // NOI18N
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(460, 520, 130, 20);

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 340, 77, 14);

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 370, 75, 14);

        jTextField11.setText(resourceMap.getString("jTextField11.text")); // NOI18N
        jTextField11.setName("jTextField11"); // NOI18N
        jPanel1.add(jTextField11);
        jTextField11.setBounds(150, 370, 130, 20);

        jTextField14.setText(resourceMap.getString("jTextField14.text")); // NOI18N
        jTextField14.setName("jTextField14"); // NOI18N
        jPanel1.add(jTextField14);
        jTextField14.setBounds(150, 340, 130, 20);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 550, 65, 14);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(330, 340, 99, 14);

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(330, 370, 99, 14);

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(330, 400, 56, 14);

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(330, 430, 99, 14);

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(330, 460, 49, 14);

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(330, 490, 62, 14);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox5.setName("jComboBox5"); // NOI18N
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(150, 550, 40, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        jComboBox6.setName("jComboBox6"); // NOI18N
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(210, 550, 80, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002" }));
        jComboBox7.setName("jComboBox7"); // NOI18N
        jPanel1.add(jComboBox7);
        jComboBox7.setBounds(310, 550, 56, 20);

        jTextField5.setText(resourceMap.getString("jTextField5.text")); // NOI18N
        jTextField5.setName("jTextField5"); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(460, 340, 120, 20);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "Applicable", "Not Applicable" }));
        jComboBox8.setName("jComboBox8"); // NOI18N
        jPanel1.add(jComboBox8);
        jComboBox8.setBounds(460, 370, 120, 20);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "Paid", "Not Paid" }));
        jComboBox9.setName("jComboBox9"); // NOI18N
        jPanel1.add(jComboBox9);
        jComboBox9.setBounds(460, 400, 120, 20);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "Day Scholar", "Hostler" }));
        jComboBox10.setName("jComboBox10"); // NOI18N
        jPanel1.add(jComboBox10);
        jComboBox10.setBounds(460, 430, 120, 20);

        jTextField8.setText(resourceMap.getString("jTextField8.text")); // NOI18N
        jTextField8.setName("jTextField8"); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(460, 490, 120, 20);

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(590, 340, 104, 14);

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(590, 400, 106, 20);

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(590, 370, 88, 14);

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        jPanel1.add(jLabel24);
        jLabel24.setBounds(590, 430, 90, 14);

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(590, 310, 70, 14);

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "LEET", "NON-LEET" }));
        jComboBox14.setName("jComboBox14"); // NOI18N
        jComboBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox14ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox14);
        jComboBox14.setBounds(150, 580, 77, 20);

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        jPanel1.add(jLabel26);
        jLabel26.setBounds(20, 580, 70, 14);

        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N
        jPanel1.add(jLabel28);
        jLabel28.setBounds(330, 310, 90, 14);

        jTextField6.setText(resourceMap.getString("jTextField6.text")); // NOI18N
        jTextField6.setName("jTextField6"); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(460, 310, 120, 20);

        jTextField9.setText(resourceMap.getString("jTextField9.text")); // NOI18N
        jTextField9.setName("jTextField9"); // NOI18N
        jPanel1.add(jTextField9);
        jTextField9.setBounds(730, 430, 130, 20);

        jTextField10.setText(resourceMap.getString("jTextField10.text")); // NOI18N
        jTextField10.setName("jTextField10"); // NOI18N
        jPanel1.add(jTextField10);
        jTextField10.setBounds(730, 400, 130, 20);

        jTextField13.setText(resourceMap.getString("jTextField13.text")); // NOI18N
        jTextField13.setName("jTextField13"); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13);
        jTextField13.setBounds(730, 370, 130, 20);

        jTextField15.setText(resourceMap.getString("jTextField15.text")); // NOI18N
        jTextField15.setName("jTextField15"); // NOI18N
        jPanel1.add(jTextField15);
        jTextField15.setBounds(730, 340, 130, 20);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "MRS.SUPREET ", "MRS.GAGANDEEP ", "MRS. DIPTI ", "MRS. JASMINE", "MISS. LOVEPREET ", "MISS AMANDEEP", "MRS.RAJVEER", " " }));
        jComboBox11.setName("jComboBox11"); // NOI18N
        jPanel1.add(jComboBox11);
        jComboBox11.setBounds(730, 310, 130, 20);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "FWS", "NON FWS" }));
        jComboBox12.setName("jComboBox12"); // NOI18N
        jPanel1.add(jComboBox12);
        jComboBox12.setBounds(240, 580, 80, 20);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "General", "OBC", "ST", "SC" }));
        jComboBox13.setName("jComboBox13"); // NOI18N
        jPanel1.add(jComboBox13);
        jComboBox13.setBounds(460, 460, 120, 20);

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "DAY SCHOLAR", "HOSTLER" }));
        jComboBox16.setName("jComboBox16"); // NOI18N
        jPanel1.add(jComboBox16);
        jComboBox16.setBounds(340, 580, 80, 20);

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(590, 470, 60, 14);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(730, 460, 180, 40);

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(590, 540, 23, 14);

        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N
        jPanel1.add(jLabel29);
        jLabel29.setBounds(590, 570, 30, 14);

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N
        jPanel1.add(jLabel30);
        jLabel30.setBounds(590, 600, 43, 14);

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "Abohar", "Agra", "Ambala", "Ahmedabad", "Alappuzha", "Alwar", "Ajitgarh", "Amritsar", "Aurangabad", "Bangalore", "Barnala", "Bathinda", "Batala", "Bharatpur", "Bhavnagar", "Bhikaner", "Bhopal", "Bhubaneshwar", "Bodh Gaya", "Calangute", "Chandigarh", "Chennai", "Chittaurgarh", "Coimbatore", "Cuttack", "Dalhousie", "Dehradun", "Delhi", "Diu-Island", "Ernakulam", "Faridabad", "Firozpur", "Gaya", "Gangtok", "Ghaziabad", "Gurgaon", "Guwahati", "Gwalior", "Haridwar", "Hoshiarpur", "Hyderabad", "Imphal", "Indore", "Jabalpur", "Jalandhar", "Jaipur", "Jaisalmer", "Jalandhar", "Jamshedpur", "Jodhpur", "Junagadh", "Kanpur", "Kanyakumari", "Kapurthala", "Khajuraho", "Khanna", "Khandala", "Kochi", "Kodaikanal", "Kolkata", "Kota", "Kottayam", "Kovalam", "Lucknow", "Ludhiana", "Madurai", "Malerkotla", "Manali", "Mangalore", "Margao", "Mathura", "Moga", "Mountabu", "Muktasar", "Mumbai", "Mussoorie", "Mysore", "Manali", "Nagpur", "Nainital", "Noida", "Ooty", "Orchha", "Panaji", "Pathankot", "Patna", "Patiala", "Phagwara", "Pondicherry", "Porbandar", "Portblair", "Pune", "Puri", "Pushkar", "Rajkot", "Rajpura", "Rameswaram", "Ranchi", "Sanchi", "Secunderabad", "Shimla", "Surat", "Thanjavur", "Thiruchchirapalli", "Thrissur", "Tirumala", "Udaipur", "Vadodra", "Varanasi", "Vasco-Da-Gama", "Vijayawada", "Visakhapatnam", "If other mention in address" }));
        jComboBox17.setName("jComboBox17"); // NOI18N
        jPanel1.add(jComboBox17);
        jComboBox17.setBounds(730, 540, 180, 20);

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu & Kashmir", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttar Pradesh", "Uttaranchal", "West Bengal", "If other mention in address" }));
        jComboBox18.setName("jComboBox18"); // NOI18N
        jPanel1.add(jComboBox18);
        jComboBox18.setBounds(730, 570, 180, 20);

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "BANGLADESH", "PAKISTAN", "NEPAL", "AFGANISTAN", "CHINA", "NEPAL", "SRI LANKA", "MYANMAR", "BHUTAN", "INDIA", "If other mention in address" }));
        jComboBox19.setName("jComboBox19"); // NOI18N
        jPanel1.add(jComboBox19);
        jComboBox19.setBounds(730, 600, 180, 20);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(940, 340, 90, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "Civil Engineering", "Mechanical Engineering", "Computer Science and Engineering", "Information Engineering", "Electrical Engineering", "Electronics and Communication Engineering", "Production Engineering" }));
        jComboBox3.setName("jComboBox3"); // NOI18N
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(150, 520, 170, 20);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(600, 260, 65, 23);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(600, 520, 70, 14);

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox15.setName("jComboBox15"); // NOI18N
        jPanel1.add(jComboBox15);
        jComboBox15.setBounds(730, 510, 100, 20);

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(940, 380, 55, 23);

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(940, 420, 61, 23);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(studentmanagement.StudentManagementApp.class).getContext().getActionMap(newrecord1.class, this);
        jButton5.setAction(actionMap.get("quit")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jPanel1.add(jButton5);
        jButton5.setBounds(950, 460, 53, 23);

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(950, 500, 67, 23);

        jLabel31.setBackground(resourceMap.getColor("jLabel31.background")); // NOI18N
        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, resourceMap.getColor("jLabel31.border.matteColor"))); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N
        jPanel1.add(jLabel31);
        jLabel31.setBounds(270, 250, 420, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//public void newrecord(personalinfotemplate T)
//{
      //    String a=jTextField1.getText();
      //    int b= 
    String name=jTextField2.getText();
    String fname=jTextField14.getText();
    String mname=jTextField11.getText();
        String collrollno=jTextField3.getText();
        int college=Integer.parseInt(collrollno);
        
        String unirollno=jTextField4.getText();
        int university=Integer.parseInt(unirollno);
    String smail=jTextField6.getText();
 //   int studentemailid=Integer.parseInt(smail);
           String scontact=jTextField5.getText();
           int Studentcontactno=Integer.parseInt(scontact);
                   String bloodgp=jTextField8.getText();
           String fathercontactno=jTextField15.getText();
         //  System.out.println("father contact=="+fcontact);
         //  int fathercontactno=Integer.parseInt(fcontact);
           
           String fmail=jTextField13.getText();
           
           String mcontact=jTextField10.getText();
           int mothercontactno=Integer.parseInt(mcontact);
           String sem=(String)jComboBox15.getSelectedItem();
           int semester1=Integer.parseInt(sem);
            String mmail=jTextField9.getText();
            String gender=(String) jComboBox1.getSelectedItem();
                  String course=(String)jComboBox2.getSelectedItem();
                 // System.out.println("course is=="+course);
                         String branch=(String) jComboBox3.getSelectedItem();
                       String dd=(String)jComboBox5.getSelectedItem();
                   int dateofbirth=    Integer.parseInt(dd);
                         String month=(String)jComboBox6.getSelectedItem();
                   
                         
                         String yy=(String)jComboBox7.getSelectedItem();
                         int year=Integer.parseInt(yy);
                      //   String leet=jComboBox14.getSelectedItem();
                             String feewai=(String) jComboBox12.getSelectedItem();
                         
                           //  String daysch=jComboBox16.getSelectedItem();
                                 String feewaiver=(String) jComboBox8.getSelectedItem();
                                             String feestatus=(String) jComboBox9.getSelectedItem();
                                             String dayhost=(String) jComboBox10.getSelectedItem();
                                             String category1=(String) jComboBox14.getSelectedItem();
                                                 
                                                         String category=(String) jComboBox13.getSelectedItem();
                                                 String category2=(String) jComboBox16.getSelectedItem();
                                                 
                                                         String section=(String) jComboBox4.getSelectedItem();
                            String advisor=(String) jComboBox11.getSelectedItem();
                            String city=(String) jComboBox17.getSelectedItem();
                            String state=(String) jComboBox18.getSelectedItem();
                             String id=(String)jTextField1.getText();
                         int id1=Integer.parseInt(id);
                             String addr=(String) jTextArea1.getText();
                            String country=(String) jComboBox19.getSelectedItem();
                            
                            
                            
                            personalinfotemplate T=new personalinfotemplate();
                          
                            
                            
T.setAddr(addr);
T.setAdvisor(advisor);
T.setBlood(bloodgp);
T.setBranch(branch);
//T.setFEECategory1(category1);
T.setCategory(category);
//T.setFEECategory2(category2);
T.setCity(city);
T.setcollegerollno(college);
T.setCountry(country);
T.setCourse(course);
T.setDay(dayhost);
T.setDateofbirth(dateofbirth);
T.setFathercont(fathercontactno);
T.setFeecategory1(category1); 
T.setFeecategory(feewai);
T.setFeecategory2(category2); 
T.setFeestatus(feestatus);
T.setFeewaiver(feewaiver);
T.setFemail(fmail);
T.setFname(fname);
T.setGender(gender);
T.setId(id1);
T.setMemail(mmail);
T.setMname(mname);
T.setMothcont(mothercontactno);
T.setName(name);
T.setSection(section);
T.setSemester(semester1);
T.setState(state);
T.setStucont(Studentcontactno);
T.setStuemail(smail);
T.setUnirollno(university);
T.setMonth(month);
T.setYear(year);



newrecordOperationDB obj=new newrecordOperationDB();
obj.Savenewrecord1(T);

                            
             JOptionPane.showMessageDialog(this, "Record Has Been Submitted Successfully");               
//String Name = (String)jComboBox1.getSelectedItem(); 
//jLabel1.setText(" " + Name); 
                            
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox14ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int studentid=Integer.parseInt(jTextField1.getText());
     
        newrecordOperationDB ll=new newrecordOperationDB();
        DBCursor cursor=ll.searchnewrecord1(studentid);
       JOptionPane.showMessageDialog(this, "Record Has Been Searching...");
        while(cursor.hasNext())
        {
           DBObject dbo= cursor.next();
            jTextField2.setText(dbo.get("Name")+"");
          jTextField14.setText(dbo.get("Fathername")+"");
          jTextField11.setText(dbo.get("Mothername")+"");
           jComboBox1.setSelectedItem(dbo.get("Gender"));
          
            jTextField3.setText(dbo.get("Collegerollno")+"");
            jTextField4.setText(dbo.get("Universityrollno")+"");
             jComboBox2.setSelectedItem(dbo.get("Course"));
              jComboBox3.setSelectedItem(dbo.get("Branch"));
           
              
            jComboBox5.setSelectedItem(dbo.get("Dateofbirth")+"");
             jComboBox6.setSelectedItem(dbo.get("Month"));
              jComboBox7.setSelectedItem(dbo.get("Year")+"");
             jComboBox14.setSelectedItem(dbo.get("FEEcategory1"));
              jComboBox12.setSelectedItem(dbo.get("FEEcategory"));
              jComboBox16.setSelectedItem(dbo.get("FEEcategory2"));
           //  jComboBox10.setSelectedItem(dbo.get("Day"));
            jTextField6.setText(dbo.get("Studentmail")+"");
             jTextField5.setText(dbo.get("Studentcontact")+"");
             jComboBox8.setSelectedItem((String)dbo.get("feewaiver"));
             jComboBox9.setSelectedItem((String)dbo.get("FEEstatus"));
             jComboBox10.setSelectedItem(dbo.get("Day Scholar/Hostler"));
             jComboBox13.setSelectedItem(dbo.get("Category"));
              jTextField8.setText((String)dbo.get("Blood"));
               jComboBox4.setSelectedItem(dbo.get("Section"));
                jComboBox11.setSelectedItem(dbo.get("Advisor")+"");
                  jTextField15.setText(dbo.get("Fathercontact")+"");
                    jTextField13.setText(dbo.get("Fathermail")+"");
                      jTextField10.setText(dbo.get("Mothercontact")+"");
                        jTextField9.setText((String)dbo.get("Mothermail"));
                          jTextArea1.setText((String)dbo.get("Address"));
                           jComboBox15.setSelectedItem(dbo.get("Semester")+"");
                            jComboBox17.setSelectedItem(dbo.get("City"));
                             jComboBox18.setSelectedItem(dbo.get("State"));
                              jComboBox19.setSelectedItem(dbo.get("Country"));
           //  jTextArea2.setText((String)dbo.get("Address"));
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);        
StudentManagementView.mainPanel.add(new studentrecord()).setVisible(true);       
repaint();  
validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);        
StudentManagementView.mainPanel.add(new newrecord1()).setVisible(true);       
repaint();  
validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    int studentid=Integer.parseInt(jTextField1.getText());
    newrecordOperationDB aa=new newrecordOperationDB();
 String name=jTextField2.getText();
    String fname=jTextField14.getText();
    String mname=jTextField11.getText();
        String collrollno=jTextField3.getText();
        int college=Integer.parseInt(collrollno);
        
        String unirollno=jTextField4.getText();
        int university=Integer.parseInt(unirollno);
    String smail=jTextField6.getText();
 //   int studentemailid=Integer.parseInt(smail);
           String scontact=jTextField5.getText();
           int Studentcontactno=Integer.parseInt(scontact);
                   String bloodgp=jTextField8.getText();
           String fathercontactno=jTextField15.getText();
        //   System.out.println("father contact=="+fcontact);
        //   int =Integer.parseInt(fcontact);
           
           String fmail=jTextField13.getText();
           
           String mcontact=jTextField10.getText();
           int mothercontactno=Integer.parseInt(mcontact);
           String sem=(String)jComboBox15.getSelectedItem();
           int semester1=Integer.parseInt(sem);
            String mmail=jTextField9.getText();
            String gender=(String) jComboBox1.getSelectedItem();
                  String course=(String)jComboBox2.getSelectedItem();
                 // System.out.println("course is=="+course);
                         String branch=(String) jComboBox3.getSelectedItem();
                       String dd=(String)jComboBox5.getSelectedItem();
                   int dateofbirth=    Integer.parseInt(dd);
                         String month=(String)jComboBox6.getSelectedItem();
                   
                         
                         String yy=(String)jComboBox7.getSelectedItem();
                         int year=Integer.parseInt(yy);
                      //   String leet=jComboBox14.getSelectedItem();
                             String feewai=(String) jComboBox12.getSelectedItem();
                         
                           //  String daysch=jComboBox16.getSelectedItem();
                                 String feewaiver=(String) jComboBox8.getSelectedItem();
                                             String feestatus=(String) jComboBox9.getSelectedItem();
                                             String dayhost=(String) jComboBox10.getSelectedItem();
                                             String category1=(String) jComboBox14.getSelectedItem();
                                                 
                                                         String category=(String) jComboBox13.getSelectedItem();
                                                 String category2=(String) jComboBox16.getSelectedItem();
                                                 
                                                         String section=(String) jComboBox4.getSelectedItem();
                            String advisor=(String) jComboBox11.getSelectedItem();
                            String city=(String) jComboBox17.getSelectedItem();
                            String state=(String) jComboBox18.getSelectedItem();
                             String addr=(String) jTextArea1.getText();
                            String country=(String) jComboBox19.getSelectedItem();
                            
                            
                            

                            personalinfotemplate T=new personalinfotemplate();
                          
                            
                            
T.setAddr(addr);
T.setAdvisor(advisor);
T.setBlood(bloodgp);
T.setBranch(branch);
//T.setFEECategory1(category1);
T.setCategory(category);
//T.setFEECategory2(category2);
T.setCity(city);
T.setcollegerollno(college);
T.setCountry(country);
T.setCourse(course);
T.setDay(dayhost);
T.setDateofbirth(dateofbirth);
T.setFathercont(fathercontactno);
T.setFeecategory1(category1); 
     
        
T.setFeecategory(feewai);
T.setFeecategory2(category2); 
T.setFeestatus(feestatus);
T.setFeewaiver(feewaiver);
T.setFemail(fmail);
T.setFname(fname);
T.setGender(gender);
T.setId(studentid);
T.setMemail(mmail);
T.setMname(mname);
T.setMothcont(mothercontactno);
T.setName(name);
T.setSection(section);
T.setSemester(semester1);
T.setState(state);
T.setStucont(Studentcontactno);
T.setStuemail(smail);
T.setUnirollno(university);
T.setMonth(month);
T.setYear(year);
aa.updatenewrecord1(T);
   JOptionPane.showMessageDialog(this, "Record Update Successfully");
   this.setVisible(false);
    StudentManagementView.mainPanel.add(new newrecord1()).setVisible(true);
    repaint();
    validate();
        /*
        int id=Integer.parseInt(jTextField1.getText());
      viewoperationDB kK=new viewoperationDB();
        DBCursor cursor=kK.searchviewrecord(id);
        while(cursor.hasNext())
        {
           DBObject dbo= cursor.next();
            jTextField2.setText(dbo.get("Name")+"");
          jTextField14.setText(dbo.get("Fathername")+"");
          jTextField11.setText(dbo.get("Mothername")+"");
           jComboBox1.setSelectedItem(dbo.get("Gender"));
          
            jTextField3.setText(dbo.get("Collegerollno")+"");
            jTextField4.setText(dbo.get("Universityrollno")+"");
             jComboBox2.setSelectedItem(dbo.get("Course"));
              jComboBox3.setSelectedItem(dbo.get("Branch"));
           
              
            jComboBox5.setSelectedItem(dbo.get("Dateofbirth")+"");
             jComboBox6.setSelectedItem(dbo.get("Month"));
              jComboBox7.setSelectedItem(dbo.get("Year"));
             jComboBox14.setSelectedItem(dbo.get("FEEcategory1"));
              jComboBox12.setSelectedItem(dbo.get("FEEcategory"));
              jComboBox16.setSelectedItem(dbo.get("FEEcategory2"));
             jComboBox10.setSelectedItem(dbo.get("Day"));
            jTextField6.setText(dbo.get("Studentmail")+"");
             jTextField5.setText(dbo.get("Studentcontact")+"");
             jComboBox8.setSelectedItem(dbo.get("feewaiver"));
             jComboBox9.setSelectedItem(dbo.get("FEEstatus"));
             jComboBox10.setSelectedItem(dbo.get("Day Scholar/Hostler"));
             jComboBox13.setSelectedItem(dbo.get("Category"));
              jTextField8.setText((String)dbo.get("Blood"));
               jComboBox4.setSelectedItem(dbo.get("Section"));
                jComboBox11.setSelectedItem(dbo.get("Advisor")+"");
                  jTextField15.setText(dbo.get("Fathercontact")+"");
                    jTextField13.setText(dbo.get("Fathermail")+"");
                      jTextField10.setText(dbo.get("Mothercontact")+"");
                        jTextField9.setText((String)dbo.get("Mothermail"));
                          jTextArea1.setText((String)dbo.get("Address"));
                           jComboBox15.setSelectedItem(dbo.get("Semester"));
                            jComboBox17.setSelectedItem(dbo.get("City"));
                             jComboBox18.setSelectedItem(dbo.get("State"));
                              jComboBox19.setSelectedItem(dbo.get("Country"));
                              
                              
                              
          //  jTextField2.setText((String)dbo.get("Name"));        sneh
          //   jTextField2.setText(dbo.get("Name")+"");                   create
            
            jTextField14.setText((String)dbo.get("noofitems"));
      //      int noofitems=integer.parseInt(noofitems);
            jTextField11.setText((String)dbo.get("priceperpiece"));
            jTextField4.setText((String)dbo.get("product"));
           jTextField5.setText((String)dbo.get("company"));
            jTextArea1.setText((String)dbo.get("addressofcompany"));}
        //    jTextField1.setText((String)dbo.get("name"));
      //      jTextField2.setText((String)dbo.get("noofitems"));    
        
        */
        
        
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox17;
    private javax.swing.JComboBox jComboBox18;
    private javax.swing.JComboBox jComboBox19;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
